// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"encoding/json"
)

type Question struct {
	ID     int32           `json:"id"`
	Title  string          `json:"title"`
	Answer json.RawMessage `json:"answer"`
	Score  json.RawMessage `json:"score"`
}
