// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"encoding/json"
)

type Question struct {
	ID     int32
	Title  string
	Answer json.RawMessage
	Score  json.RawMessage
}
