// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: question.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getQuestionScoreByID = `-- name: GetQuestionScoreByID :one

SELECT (
        q.score ->> $1 :: TEXT
    ) :: INT AS score
FROM question q
WHERE q.id = $2
`

type GetQuestionScoreByIDParams struct {
	Answer string `json:"answer"`
	ID     int32  `json:"id"`
}

func (q *Queries) GetQuestionScoreByID(ctx context.Context, arg GetQuestionScoreByIDParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getQuestionScoreByID, arg.Answer, arg.ID)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const getQuestions = `-- name: GetQuestions :many

SELECT q.id, q.title, q.answer FROM question q ORDER BY q.id
`

type GetQuestionsRow struct {
	ID     int32           `json:"id"`
	Title  string          `json:"title"`
	Answer json.RawMessage `json:"answer"`
}

func (q *Queries) GetQuestions(ctx context.Context) ([]GetQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionsRow
	for rows.Next() {
		var i GetQuestionsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Answer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
